### ISSUE TITLE
TOTP: Issuer must not contain a colon.

### ISSUE THREAD

**Issue by kantgym** [catalyst/moodle-tool_mfa#181]
My Moodle Sitename had a ":" in its name. Thus when trying to setup TOTP for a user I received the error  "Issuer must not contain a colon."

Maybe instead of just throwing an error, replacing/escaping the ":" would be better, since ":" is allowed to be put in the sites name.

At least mentioning the requirement not to have ":" in the site-name within the documentation would be nice.

Even better, if the issuer transfered to the TOTP-App would be configurable from the subplugin. Maybe also the format of the account name.

Thanks for this wonderful plugin.

**Comment by Peterburnett** [comment]
Hi @kantgym, thanks for the feedback! This issue appears to arise from the thirdparty libraries restrictions on the characters that can be passed as parameters to the library. As you said, possibly escaping/stripping this character is a solution to this problem.

PR's are welcome to fix this issue if you wish to move this along faster, but this has been added to our backlog.
Thanks

**Comment by yetanotherbug** [comment]
I'd like to expand this bug. This issue also breaks the TOTP factor whenever `$CFG->wwwroot` is set to an URL that contains a port number as part of the netloc (in the sense of RFC 1808).

So wwwroots of the form http://localhost:8080, https://127.0.0.1:8443, https://hurdurnonstandardsslport.com:8888 all cause the TOTP factor to not be configurable because of this code in factor/totp/classes/factor.php:

```php
    public function generate_totp_uri($secret) {
        global $USER, $SITE, $CFG;
        $domain = str_replace('http://', '', str_replace('https://', '', $CFG->wwwroot)); // <----------- bad code, leaves a colon if a port was specified
        $issuer = $SITE->fullname.' '.$domain;
        $totp = TOTP::create($secret);
        $totp->setLabel($USER->username);
        $totp->setIssuer($issuer);
        return $totp->getProvisioningUri();
    }
```

Error invetiably in the user MFA preferences (moodle 3.9 as of v3.9.1-310-g535523f21f8, this plugin as of 2020021401-59-gf6850ee):

```
Exception - Issuer must not contain a colon.

Error code: generalexceptionmessage

Stack trace:

    line 2752 of /admin/tool/mfa/factor/totp/extlib/Assert/Assertion.php: Assert\InvalidArgumentException thrown
    line 1794 of /admin/tool/mfa/factor/totp/extlib/Assert/Assertion.php: call to Assert\Assertion::createException()
    line 226 of /admin/tool/mfa/factor/totp/extlib/OTPHP/ParameterTrait.php: call to Assert\Assertion::false()
    line 185 of /admin/tool/mfa/factor/totp/extlib/OTPHP/ParameterTrait.php: call to OTPHP\OTP->OTPHP\{closure}()
    line 100 of /admin/tool/mfa/factor/totp/extlib/OTPHP/ParameterTrait.php: call to OTPHP\OTP->setParameter()
    line 70 of /admin/tool/mfa/factor/totp/classes/factor.php: call to OTPHP\OTP->setIssuer()
    line 81 of /admin/tool/mfa/factor/totp/classes/factor.php: call to factor_totp\factor->generate_totp_uri()
    line 136 of /admin/tool/mfa/factor/totp/classes/factor.php: call to factor_totp\factor->generate_qrcode()
    line 70 of /admin/tool/mfa/classes/local/form/setup_factor_form.php: call to factor_totp\factor->setup_factor_form_definition_after_data()
    line 986 of /lib/formslib.php: call to tool_mfa\local\form\setup_factor_form->definition_after_data()
    line 107 of /admin/tool/mfa/action.php: call to moodleform->display()
```

For the record, this is not happening because we have weird ports in production, but I noticed this because of a local development stack with docker-compose :) 

Because we already deploy plugins like this as a mixin I will be having a patch ready for our use; if I can find the time to upstream it I'll open a PR.
