### ISSUE TITLE
Not compatible with 3.9+

### ISSUE THREAD

**Issue by karnakitab** [catalyst/moodle-tool_mfa#212]
Moodle 3.9
Nginx 1.18
PHP 7.4
PostgreSQL 12

Cloned the repository to admin/tool/mfa, enabled no setup and authenticator otp. But can not see any link in User>Preferences to set up the authenticator/MFA. Even upon clearing the cache no success. I think it is not yet compatible with moodle 3.9.

**Comment by brendanheywood** [comment]
I can't reproduce this, works fine me on bleeding edge master

Can you provide any more detail?

**Comment by karnakitab** [comment]
It is working now as intended. Maybe error from my side. Thanks @brendanheywood for your valuable time.

**Comment by osel21** [comment]
Same issue here with Moodle 3.8 @brendanheywood how can I manage this ? 
I choose a TOTP authentication but I can't find the TOTP Factor Setup in order to add users device. 
It is possible to automatically generate the authentication code for users uploaded by csv ? 

Thanks in advance for your support
