### ISSUE TITLE
Replace term 'WebAuthn' in language strings to prevent confusion

### ISSUE THREAD

**Issue by alexmorrisnz** [catalyst/moodle-tool_mfa#399]
Using the term 'WebAuthn' could cause confusion with users who aren't familiar with the term.
Perhaps it should be replaced with 'Authenticator', or some other term?

For reference, here's what it looks like on Moodle 3.9:
![Screenshot from 2023-06-09 13-10-31](https://github.com/catalyst/moodle-tool_mfa/assets/6424711/17aea9d9-715f-45d9-a705-fc092918de85)
![Screenshot from 2023-06-09 13-10-50](https://github.com/catalyst/moodle-tool_mfa/assets/6424711/9f3d8d7b-b457-4eca-8379-dc4191ec339a)
![Screenshot from 2023-06-09 13-10-02](https://github.com/catalyst/moodle-tool_mfa/assets/6424711/afc34222-d2eb-471c-b2cf-c3c4b57f320b)

**Comment by keevan** [comment]
`Authenticator` might be confusing with current Authenticator applications (e.g. on some hardware, such as a phone) which are mainly used for TOTP codes (6 digit code). 

Perhaps there needs to be some supplementary details on common implementations.

**Comment by danmarsden** [comment]
options include:
"Security keys" -> (github uses this.)
"Hardware token" 


I lean towards "hardware token" myself... but either would be better than "Webauthn"

**Comment by abias** [comment]
Thank you for starting this discussion.

For FIDO2 hardware, I would prefer "security keys" which Dan proposed, especially if a big platform like Github uses it as well. However, this won't necessarily cover other authenticator hardware, especially not the internal solutions.

The most important thing is that end users do not have to care / think about any technical protocol / implementation. And the local Moodle admins might know better which terms their users understand. That's why I would like to propose to allow the admin to customize the label directly in the factor settings.

**Comment by abias** [comment]
Hi @danmarsden ,

thank you for changing the term to "Security key" now.

I spotted one place on the "Setup security key" page where the term was not replaced:

![grafik](https://github.com/catalyst/moodle-tool_mfa/assets/1092118/29bf7dbb-5ad3-4ea5-9248-f00ffffe4fcd)

I am unable to re-open this issue, but would like to replace this term there as well.
