### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Unknown method called against tool_mfa\output\renderer :: guide_link

### ISSUE THREAD

**Issue by 0kn0t0K** [catalyst/moodle-tool_mfa#455]
Hi,

After an Moodle upgrade to 4.3.3 I'm now getting this error at the bottom of  the "E-Mail Factor Enter verification code for confirmation"  page.

_Coding error detected, it must be fixed by a programmer: Unknown method called against tool_mfa\output\renderer :: guide_link_

MFA plugin version 2023080100

Note,  MFA still works, but would like to remove the error.

Any ideas on what the issue is here?

Paul

**Comment by husseinAllaham** [comment]
> Hi,
> 
> After an Moodle upgrade to 4.3.3 I'm now getting this error at the bottom of the "E-Mail Factor Enter verification code for confirmation" page.
> 
> _Coding error detected, it must be fixed by a programmer: Unknown method called against tool_mfa\output\renderer :: guide_link_
> 
> MFA plugin version 2023080100
> 
> Note, MFA still works, but would like to remove the error.
> 
> Any ideas on what the issue is here?
> 
> Paul

I'm facing the same issue with Moodle 4.3, any suggestion?

**Comment by danmarsden** [comment]
Tool_mfa was initially developed by us as a 3rd party plugin but since 4.3 is now included in the core Moodle release - any issues you have with mfa on a 4.3 (or higher version) should be reported to the moodle tracker (tracker.moodle.org) so I'm closing this one off.  If you have previously installed tool_mfa on a 4.2 or older site and have now upgraded to 4.3 - make sure you haven't overwritten any of the core Moodle files with the version available here in github - thanks.
