### ISSUE TITLE
Bug wantsurl of Go to your original URL: http://moodle.local/lib/ajax/service.php?sesskey=xxx&info=core_fetch_notifications

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#82]
If you do anything interesting trying to break it then it overwrites your wants url with an ajax url

**Comment by Peterburnett** [comment]
This may now be invalid. The link that gets broken on the user-preferences page may no longer be in use. Users are no longer forced to this page when logging in when in gracemode, instead they are given a link to this page, from their wantsurl. This may be dead code, unless there is a method to access that page that I have missed, or the bug is present elsewhere. I was unable to replicate
